services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: urlshortener
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3

  backend:
    build: ./backend
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: urlshortener
      DB_USER: postgres
      DB_PASSWORD: 123456
      PORT: 8082
      BASE_URL: http://localhost:8082
      RATE_LIMIT_WINDOW_MS: 3600000
      RATE_LIMIT_MAX: 10
    ports:
      - "8082:8082"
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build: ./frontend
    environment:
      REACT_APP_API_URL: http://localhost:8082
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  postgres_data:
